//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudioGA
    {
        public int idAudioGA { get; set; }
        public Nullable<int> idPacienteGA { get; set; }
        public string NoExpediente { get; set; }
        public string D125 { get; set; }
        public string D250 { get; set; }
        public string D500 { get; set; }
        public string D1000 { get; set; }
        public string D2000 { get; set; }
        public string D4000 { get; set; }
        public string D8000 { get; set; }
        public string D12000 { get; set; }
        public string I125 { get; set; }
        public string I250 { get; set; }
        public string I500 { get; set; }
        public string I1000 { get; set; }
        public string I2000 { get; set; }
        public string I4000 { get; set; }
        public string I8000 { get; set; }
        public string I12000 { get; set; }
    
        public virtual PacienteGA PacienteGA { get; set; }
    }
}
