//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallCenter()
        {
            this.Tipificaciones = new HashSet<Tipificaciones>();
        }
    
        public int idCallCenter { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
        public string Rechazado { get; set; }
        public Nullable<int> Llamadas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tipificaciones> Tipificaciones { get; set; }
    }
}
