//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarruselMedico
    {
        public int idCarruselMedico { get; set; }
        public Nullable<System.DateTime> SignosVitales { get; set; }
        public Nullable<System.DateTime> Audiologia { get; set; }
        public Nullable<System.DateTime> Oftalmologia { get; set; }
        public Nullable<System.DateTime> Cardiologia { get; set; }
        public Nullable<System.DateTime> Laboratorio { get; set; }
        public Nullable<System.DateTime> Odontologia { get; set; }
        public Nullable<System.DateTime> HistoriaClinca { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public Nullable<System.DateTime> Fin_SignosVitales { get; set; }
        public Nullable<System.DateTime> Fin_Audiologia { get; set; }
        public Nullable<System.DateTime> Fin_Oftalmologia { get; set; }
        public Nullable<System.DateTime> Fin_Cardiologia { get; set; }
        public Nullable<System.DateTime> Fin_Laboratorio { get; set; }
        public Nullable<System.DateTime> Fin_Odontologia { get; set; }
        public Nullable<System.DateTime> Fin_HistoriaClinica { get; set; }
        public Nullable<System.DateTime> InicioCarrusel { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
