//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class CERTIFICADO
    {
        public int idCertificado { get; set; }
        public string Nombre { get; set; }
        public string Pasaporte { get; set; }
        public string Respuesta { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<System.DateTime> FechaToma { get; set; }
        public string Sexo { get; set; }
        public string Usuario { get; set; }
    }
}
