//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConteoDoctores2
    {
        public int idConteoDoctor { get; set; }
        public string Doctor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Citas { get; set; }
    }
}
