//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictamenESP
    {
        public int idDictamenESP { get; set; }
        public byte[] DictamenArchivo { get; set; }
        public Nullable<int> idPacienteESP { get; set; }
    
        public virtual PacienteESP PacienteESP { get; set; }
    }
}
