//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPI
    {
        public int idEPI { get; set; }
        public string NombrePaciente { get; set; }
        public byte[] BytesArchivo { get; set; }
        public Nullable<int> NoFolio { get; set; }
        public string TipoEPI { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaExpediente { get; set; }
        public Nullable<System.DateTime> InicioCaptura { get; set; }
        public Nullable<System.DateTime> FinalCaptura { get; set; }
        public string Doctor { get; set; }
        public string Sucursal { get; set; }
        public string Usuario { get; set; }
        public byte[] Dictamen { get; set; }
        public string Capturista { get; set; }
    }
}
