//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPI_A_NoPatologicos
    {
        public int idNoPatologicos { get; set; }
        public string VacunasCompletas { get; set; }
        public string EstadoCivil { get; set; }
        public string Religion { get; set; }
        public string Escolaridad { get; set; }
        public string Hijos { get; set; }
        public Nullable<int> idPaciente { get; set; }
        public string PadecimientoActual { get; set; }
        public string ESP_PadecimientoActual { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
