//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Epi_Oftalmologia
    {
        public int idOftalmologia { get; set; }
        public string IzquierdoAVC { get; set; }
        public string IzquierdoAVM { get; set; }
        public string IzquierdoAVL { get; set; }
        public string DerechoAVC { get; set; }
        public string DerechoAVM { get; set; }
        public string DerechoAVL { get; set; }
        public string AgudezaVisual { get; set; }
        public string Estereopsis { get; set; }
        public string CartaAccidentes { get; set; }
        public string MovimientosOculares { get; set; }
        public string CampoVisual { get; set; }
        public string DerechoRP { get; set; }
        public string IzquierdoRP { get; set; }
        public string Cromatica { get; set; }
        public Nullable<int> idPaciente { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
