//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPI_GA
    {
        public int idEPI_GA { get; set; }
        public Nullable<int> idPacienteGA { get; set; }
        public string NoExpediente { get; set; }
        public string Genero { get; set; }
        public string Sistolica { get; set; }
        public string Diastolica { get; set; }
        public string Cardiaca { get; set; }
        public string Respiratoria { get; set; }
        public string Temperatura { get; set; }
        public string Peso { get; set; }
        public string Estatura { get; set; }
        public string Cintura { get; set; }
        public string Cuello { get; set; }
        public string Grasa { get; set; }
        public string Glucosa { get; set; }
        public string Hemoglobina { get; set; }
        public string Ritmo { get; set; }
        public string Frecuencia { get; set; }
        public string Eje { get; set; }
        public string PR { get; set; }
        public string QT { get; set; }
        public string QRS { get; set; }
        public string OndaP { get; set; }
        public string OndaT { get; set; }
        public string AVCD { get; set; }
        public string AVCI { get; set; }
        public string AVID { get; set; }
        public string AVII { get; set; }
        public string AVLD { get; set; }
        public string AVLI { get; set; }
        public string Lentes { get; set; }
        public string Estereopsis { get; set; }
        public string Carta { get; set; }
        public string CampoVisual { get; set; }
        public string MovOculares { get; set; }
        public string RPD { get; set; }
        public string RPI { get; set; }
        public string Nota { get; set; }
        public string TestVC { get; set; }
        public string MadreVive { get; set; }
        public string PadreVive { get; set; }
        public string HermanosViven { get; set; }
        public string VacCompletas { get; set; }
        public string ECivil { get; set; }
        public string Religion { get; set; }
        public string Escolaridad { get; set; }
        public string Hijos { get; set; }
        public string ECongenita { get; set; }
        public string EspDiag { get; set; }
        public string Alergia { get; set; }
        public string Diabetes { get; set; }
        public string DiagHipArt { get; set; }
        public string Alcohol { get; set; }
        public string Fuma { get; set; }
        public string Drogas { get; set; }
        public string UsaLentes { get; set; }
        public string TLentes { get; set; }
        public string URegla { get; set; }
        public string Embarazos { get; set; }
        public string Abortos { get; set; }
        public string Parto { get; set; }
        public string Cesarea { get; set; }
        public string IVSexual { get; set; }
        public string Patologias { get; set; }
        public string Interpretacion { get; set; }
        public string NotaMedica { get; set; }
        public string D125 { get; set; }
        public string D250 { get; set; }
        public string D500 { get; set; }
        public string D1000 { get; set; }
        public string D2000 { get; set; }
        public string D4000 { get; set; }
        public string D8000 { get; set; }
        public string D12000 { get; set; }
        public string I125 { get; set; }
        public string I250 { get; set; }
        public string I500 { get; set; }
        public string I1000 { get; set; }
        public string I2000 { get; set; }
        public string I4000 { get; set; }
        public string I8000 { get; set; }
        public string I12000 { get; set; }
    
        public virtual PacienteGA PacienteGA { get; set; }
    }
}
