//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class EPI_ExploracionFisica
    {
        public int idExploracionFisica { get; set; }
        public string Romberg { get; set; }
        public string PuntaNariz { get; set; }
        public string Estrabismo { get; set; }
        public string Soplo { get; set; }
        public string Amputaciones { get; set; }
        public string Protesis { get; set; }
        public Nullable<int> idPaciente { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
