//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expediente
    {
        public int idEPI { get; set; }
        public string NombreEPI { get; set; }
        public byte[] Archivo { get; set; }
        public Nullable<int> NoFolio { get; set; }
        public string Tipo { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> idDoctor { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Doctores Doctores { get; set; }
        public virtual Sucursales Sucursales { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
