//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuellasRandom
    {
        public int idHuella { get; set; }
        public byte[] Huella2 { get; set; }
        public byte[] Huella3 { get; set; }
        public byte[] Huella7 { get; set; }
        public byte[] Huella8 { get; set; }
    }
}
