//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencias
    {
        public int idIncidencia { get; set; }
        public string NombrePaciente { get; set; }
        public string Expediente { get; set; }
        public string Capturista { get; set; }
        public string Incidencia { get; set; }
        public Nullable<System.DateTime> FechaIncidencia { get; set; }
        public Nullable<int> idEPI { get; set; }
    
        public virtual EPI EPI { get; set; }
    }
}
