//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidenciaPaciente
    {
        public int idComentario { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> idCaptura { get; set; }
    
        public virtual Captura Captura { get; set; }
    }
}
