//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_Movimientos
    {
        public int idlog_Movimientos { get; set; }
        public string Movimiento { get; set; }
        public Nullable<int> idLogInicioGestor { get; set; }
    
        public virtual log_InicioGestor log_InicioGestor { get; set; }
    }
}
