//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacienteGA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PacienteGA()
        {
            this.AudioGA = new HashSet<AudioGA>();
            this.EPI_GA = new HashSet<EPI_GA>();
        }
    
        public int idPacienteGA { get; set; }
        public string Nombre { get; set; }
        public string CURP { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Folio { get; set; }
        public string HASH { get; set; }
        public string Genero { get; set; }
        public string Estatura { get; set; }
        public string NoExpediente { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string TipoPago { get; set; }
        public string Recepcionista { get; set; }
        public string Asistencia { get; set; }
        public string CancelaComentario { get; set; }
        public string Entregado { get; set; }
        public string ReferidoPor { get; set; }
        public Nullable<System.DateTime> FechaCita { get; set; }
        public string Metra { get; set; }
        public string Solicita { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaReferencia { get; set; }
        public string NoOrden { get; set; }
        public string EstatusPago { get; set; }
        public string Referencia { get; set; }
        public Nullable<int> idCanal { get; set; }
        public string Canal { get; set; }
        public string CC { get; set; }
        public string CarruselMedico { get; set; }
        public string TipoTramite { get; set; }
        public string TipoLicencia { get; set; }
        public string Sucursal { get; set; }
        public string Doctor { get; set; }
        public string EstatusCaptura { get; set; }
        public string Capturista { get; set; }
        public Nullable<System.DateTime> InicioCaptura { get; set; }
        public Nullable<System.DateTime> FinalCaptura { get; set; }
        public Nullable<System.DateTime> PausaInicio { get; set; }
        public Nullable<System.DateTime> PausaFinal { get; set; }
        public Nullable<int> Duracion { get; set; }
        public string Aptitud { get; set; }
        public string ComentarioAptitud { get; set; }
        public Nullable<System.DateTime> FechaVigencia { get; set; }
        public string ALT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AudioGA> AudioGA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPI_GA> EPI_GA { get; set; }
    }
}
