//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcionista
    {
        public int idRecepcionista { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idSucursal { get; set; }
    
        public virtual Sucursales Sucursales { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
