//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkeedaPK
    {
        public int idSkeeda { get; set; }
        public Nullable<System.DateTime> Scheduled_start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<double> Duration__minutes_ { get; set; }
        public Nullable<double> Spaces_count { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public Nullable<double> Price { get; set; }
        public string Payment_status { get; set; }
        public string Holder_first_name { get; set; }
        public string Holder_last_name { get; set; }
        public string Holder_organization { get; set; }
        public string Holder_telephone { get; set; }
        public string Holder_email { get; set; }
        public string Holder_tags { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Gateway_charge_reference { get; set; }
        public string Spaces { get; set; }
        public string Mail__Custom_field_1_ { get; set; }
        public string Tel__Custom_field_2_ { get; set; }
        public string TipoLicenc__Custom_field_3_ { get; set; }
        public string TipoTramit__Custom_field_4_ { get; set; }
        public string TipoPago__Custom_field_5_ { get; set; }
        public string RefPagoOxx__Custom_field_6_ { get; set; }
        public string Ord_Num__Custom_field_7_ { get; set; }
        public string FecNac__Custom_field_8_ { get; set; }
        public string Estado__Custom_field_9_ { get; set; }
        public string Ciudad__Custom_field_10_ { get; set; }
        public string Visión__Custom_field_11_ { get; set; }
        public string Tiroides__Custom_field_12_ { get; set; }
        public string Diabetes__Custom_field_13_ { get; set; }
        public string Hipertens__Custom_field_14_ { get; set; }
        public string Audicion__Custom_field_15_ { get; set; }
        public string EnfCronica__Custom_field_16_ { get; set; }
        public string Embarazo__Custom_field_17_ { get; set; }
        public string Referido__Custom_field_18_ { get; set; }
        public string Otro___Custom_field_19_ { get; set; }
        public string CheckCita__Custom_field_20_ { get; set; }
        public string DrVeracruz__Custom_field_21_ { get; set; }
        public string DrSatelite__Custom_field_22_ { get; set; }
        public string DrLindavis__Custom_field_23_ { get; set; }
    }
}
