//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        public int idSolicitud { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> idProducto { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> idConsultorio { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<int> idMetodoPago { get; set; }
        public string ReferenciaOXXO { get; set; }
        public string ReferenciaSPEI { get; set; }
        public string NoOrden { get; set; }
        public Nullable<int> idEstatusSolicitud { get; set; }
        public string TerminacionTarjeta { get; set; }
        public Nullable<int> idTipoTarjeta { get; set; }
        public string CodigoAutorizacion { get; set; }
        public Nullable<int> Subtotal { get; set; }
        public Nullable<int> idComision { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Comision Comision { get; set; }
        public virtual EstatusSolicitud EstatusSolicitud { get; set; }
        public virtual MetodoPago MetodoPago { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual TipoTarjeta TipoTarjeta { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Consultorios Consultorios { get; set; }
    }
}
