//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT_iCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipificaciones
    {
        public int idTipificacion { get; set; }
        public string Nombre { get; set; }
        public string Operador { get; set; }
        public Nullable<System.DateTime> FechaLlamada { get; set; }
        public string Tipificacion { get; set; }
        public Nullable<int> idCallCenter { get; set; }
    
        public virtual CallCenter CallCenter { get; set; }
    }
}
